FROM python:3.11-slim

WORKDIR /usr/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DBT_PROFILES_DIR=/usr/app/dbt

RUN pip install --no-cache-dir "dbt-duckdb>=1.8.1,<2.0.0"

COPY dbt /usr/app/dbt

CMD ["dbt", "--version"]
